### ISSUE TITLE
Doesn't work on FF2

### ISSUE THREAD

**Issue by Pierce0318** [noskill-io/ffpr-tool#3]
Doesn't work on FF2 (Error: Lookup Table Speed: not found. Ensure you are modifying the original GameAssembly.dll)
But I never even touched that file.

Log:
√ Please choose a game speed. Classic or Fast should result in less stutter while walking. » Classic
Base Speed: replacing 8fc2753e with 2db29d3e
Error: Lookup Table Speed: not found. Ensure you are modifying the original GameAssembly.dll
    at replaceSingleOccurrence (C:\snapshot\ffpr-tool\dist\app.js:69:15)
    at C:\snapshot\ffpr-tool\dist\app.js:48:27
    at Array.forEach (<anonymous>)
    at main (C:\snapshot\ffpr-tool\dist\app.js:47:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by Pierce0318** [comment]
...and no. I did not accidentally use the one for ff5-ff6 or anything.

**Comment by keedalien** [comment]
Having the same issue. Any fixes?

**Comment by scrabman86** [comment]
I had to pull the pre-updated version of FFII PR using the Steam nav console and then it worked on the older exe.

Chuck this into a browser to open it in Steam: steam://nav/console

Here's the command; it takes a fair bit of time and says "Depot download complete: <Filepath>"
download_depot 1173780 1173781 7154531248258426687

When it's done, go to the filepath in explorer and copy the files back over the FFII-PR install folder. They won't get overwritten unless SE ever does another update or you verify the files.

**Comment by ShonaSoF** [comment]
I'm afraid this problem still exists in 2024. I tried pulling a modded copy of GameAssembly.dll over from one of the other PRs, but then 2 wouldn't launch at all.

**Comment by Glurak18** [comment]
Same Problem here. FF2 dont work. I think it needs an update.

**Comment by Glurak18** [comment]
Same Final Fantasy II dont work with that tool sadly.

**Comment by ddubs13** [comment]
This tool is outdated. Use this tool instead.

https://github.com/d3xMachina/FFPR-Fix

**Comment by ShonaSoF** [comment]
> This tool is outdated. Use this tool instead.
> 
> https://github.com/d3xMachina/FFPR-Fix

Appreciated! Thank you.
